version: '3.9'
services:
  db:
    image: postgres:17-alpine3.22
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: phpmarketplace
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

networks:
  php-marketplace-network:
    driver: bridge
    external: false

volumes:
  pgdata: